-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbUdDdtpsYZBV4z7F
dVn/l0NiD83XfLokcx/127q2/jugCgYIKoZIzj0DAQehRANCAAQK98Al5aBuBWRs
DBHKaQUg6aNVD/PCgyAajjdyhkEG+/2SemJFHhHStXeeg83jMh11nD6BwhYzF3vT
Dht/ZChi
-----END PRIVATE KEY-----